name: Update Github Stats Gist
on:
    schedule:
        - cron: '0 * * * *'
    push:
        branches: master

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npx github-stats-box
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIST_ID: ${{ secrets.GIST_ID }}
                  ALL_COMMITS: ${{ secrets.ALL_COMMITS }}
