# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: Metrics
on:
  # Schedule updates (Everyday)
  schedule: [{cron: "0 6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: bokub
          template: classic
          base: header
          config_timezone: Europe/Paris
          config_display: large
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          committer_gist: a299e5bf8043cf7bc08284f339e52468
          output_action: gist
